# Generated by Django 4.2.15 on 2024-08-14 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='data',
        ),
        migrations.AddField(
            model_name='temperature',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
